<?php

/**
 * Output a link generated by md_get_link().
 *
 * @since 4.3.5
 */

function md_link( $fields, $p = '' ) {
	echo md_get_link( $fields, $p );
}

/**
 * Would you believe all the things a link can do? Customize the output
 * of a link or button displayed from any MD button settings page or
 * the md_get_link and md_link() function with passed data.
 *
 * @since 4.3.5
 */

function md_get_link( $fields, $p = '' ) {
	$html = $attrs = '';
	$styles = array();
	$fields = wp_parse_args( $fields, array(
		'type' => 'url',
		'style' => 'link',
		'area' => '',
		'name' => '',
		'subtitle' => '',
		'icon' => '',
		'url' => '',
		'phone' => '',
		'size' => '',
		'color' => '',
		'popup' => '',
		'popup_args' => array(),
		'html' => '',
		'content' => '',
		'attributes' => array(),
		'classes' => '',
		'visibility' => array(),
		'button_style' => array(),
		'toggle' => array(
			'hide_label' => '',
			'hide_label_mobile' => ''
		)
	) );

	if ( empty( $fields['type'] ) )
		$fields['type'] = 'url';

	if ( ! md_check_condition( $fields['visibility'] ) )
		return;

	if ( empty( $fields['name'] ) && empty( $fields['icon'] ) && empty( $fields['content'] ) )
		return;

	$allowed_html = array( 'a', 'button', 'span' );
	$h = in_array( $fields['html'], $allowed_html, true ) ? $fields['html'] : 'span';
	$classes = array( 'link' );
	$has_wrap = $fields['name'] && $fields['subtitle'];

	// Plain link

	if ( $fields['type'] == 'url' && $fields['url'] ) {
		$h = 'a';
		$attrs .= ' href="' . esc_url( $fields['url'] ) . '"';
		$attrs .= isset( $fields['settings']['new'] ) ? ' target="_blank"' : '';
	}

	// Phone number

	elseif ( $fields['type'] == 'phone' ) {
		$h = 'a';
		$attrs .= ' href="tel:' . esc_html( $fields['phone'] ) . '"';
		$classes[] = $fields['icon'] = 'phone';

		if ( empty( $fields['name'] ) )
			$fields['name'] = esc_html( $phone );
	}

	// Popup

	elseif ( $fields['type'] == 'popup' && $fields['popup'] && function_exists( 'md_popup' ) ) {
		$h = $fields['html'] ? $h : 'button';
		$popup_args = wp_parse_args( $fields['popup_args'], array( 'id' => $fields['popup'] ) );
		$popup_args['id'] = $fields['popup'];
		$attrs .= $h === 'button' ? ' type="button"' : '';
		$attrs .= ' data-popup="popup_' . esc_attr( $fields['popup'] ) . '"';
		$classes[] = 'popup-trigger';
		md_popup( $popup_args );
	}

	// Turn link into a button

	if ( $fields['style'] == 'button' ) {
		$classes[] = 'button';

		if ( $fields['size'] )
			$classes[] = 'button-' . $fields['size'];

		if ( $fields['button_style'] )
			foreach ( $fields['button_style'] as $button_style => $val )
				if ( $val )
					$classes[] = "button-$button_style";

		if ( $fields['color'] ) {
			if ( ! empty( $fields['button_style']['outline'] ) ) {
				if ( $class = md_color_class( $fields['color'], 'color' ) ) {
					$classes[] = $class;
					$classes[] = md_color_class( $fields['color'], 'border_color' );
				}
				elseif ( $hex = md_color_hex( $fields['color'] ) )
					$styles['color'] = $styles['border_color'] = $hex;
			}
			else {
				if ( $class = md_color_class( $fields['color'], 'bg_color' ) )
					$classes[] = $class;
				elseif ( $hex = md_color_hex( $fields['color'] ) )
					$styles['bg_color'] = $hex;
			}
		}
	}

	// Set a color on regular links

	elseif ( $fields['color'] ) {
		if ( $class = md_color_class( $fields['color'] ) )
			$classes[] = $class;
		elseif ( $hex = md_color_hex( $fields['color'] ) )
			$styles['color'] = $hex;
	}

	// Visibility options

	if ( ! empty( $fields['toggle']['hide_label'] ) )
		$classes[] = 'hide-label';

	if ( ! empty( $fields['toggle']['hide_label_mobile'] ) )
		$classes[] = 'hide-label-mobile';

	foreach ( md_get_visibility_classes( $fields['visibility'] ) as $class )
		$classes[] = $class;

	if ( $fields['icon'] )
		$classes[] = 'has-icon';

	if ( ! empty( $fields['settings']['icon_end'] ) )
		$classes[] = 'reverse';

	if ( $fields['classes'] )
		$classes = array_merge( $classes, (array) $fields['classes'] );

	if ( $fields['attributes'] )
		foreach ( $fields['attributes'] as $attribute => $value ) {
			$attribute = sanitize_key( $attribute );

			if ( ! $attribute || in_array( $attribute, array( 'class', 'style' ), true ) || $value === false || ! is_scalar( $value ) )
				continue;

			$attrs .= $value === true ? ' ' . $attribute : ' ' . $attribute . '="' . esc_attr( $value ) . '"';
		}

	// Finally, render link with its final attributes

	$attrs .= ' class="' . esc_attr( join( ' ', $classes ) ) . '"';
	$attrs .= md_style( $styles );

	$html =
		"<$h{$attrs}>".
		( $fields['content'] ? wp_kses_post( $fields['content'] ) :
			( $fields['icon'] ? md_icon( $fields['icon'], array( 'classes' => 'link-icon' ) ) : '' ).
			( $has_wrap ? '<span class="link-wrap">' : '' ).
			( $fields['name'] ? '<span class="link-name">' . wp_kses_post( $fields['name'] ) . '</span>' : '' ).
			( $fields['subtitle'] ? '<span class="link-subtitle">' . wp_kses_post( $fields['subtitle'] ) . '</span>' : '' ).
			( $has_wrap ? '</span>' : '' )
		).
		"</$h>";

	return $html;
}
